language: node_js
node_js:
- node
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: tempmon.arabadjikova.com
  acl: public_read
  on:
    repo: mbelianov/TempMonUI
